### ISSUE TITLE
[Suggestion] SetSourceUri Support Stream

### ISSUE THREAD

**Issue by HanbGao** [XamlAnimatedGif/XamlAnimatedGif#103]
Consider the image path support Stream.

**Comment by thomaslevesque** [comment]
Hi @HanbGao,

Could you be more specific? There's already a `SetSourceStream` method (and a `SourceStream` attached property) for this purpose.

**Comment by HanbGao** [comment]
Sorry,I had found it, thank you.In the and, please check the bug which can not at the first frame when pause a gif image.
