### ISSUE TITLE
Loading Progress

### ISSUE THREAD

**Issue by ChRocheFR** [XamlAnimatedGif/XamlAnimatedGif#108]
First, thanks for this project.

I have some trouble with big files. They take lot of time to load, and I would like to know if there is a way to report loading progress in any way. In this project, users browse various images, and can delete them afterwards. Or when the gif is not completely loaded, the app crash on deleting the file.
Thanks in advance

**Comment by thomaslevesque** [comment]
Hi @ChRocheFR,

> I have some trouble with big files. They take lot of time to load, and I would like to know if there is a way to report loading progress in any way.

How long is "a lot of time"? How big are the images?

There's a `Loaded` event in `AnimationBehavior`, and a `DownloadProgress` for images that are loaded from a HTTP URI, but that's it. Loading the image from a local file shouldn't take long, so there's no progress indication. I'll try to see what is taking so long.

> Or when the gif is not completely loaded, the app crash on deleting the file.

The best option to solve this is probably to use `SourceStream` instead of `SourceUri`. This way you can explicitly close the stream when you need to.

**Comment by thomaslevesque** [comment]
I notice the same problem on my machine, but only when the debugger is attached... If I run without debugging, the image loads almost instantly. Is it still slow for you when you run without debugging?

**Comment by ChRocheFR** [comment]
I will try to identify the size which cause the problem, but the loading time exceeds sometimes 4 seconds and I only work with local file and in release mode without Visual Studio.
Il will test the SourceStream and will come back to you after this.
By the way, this version is still more stable than the previous WpfAnimatedGif.

**Comment by ChRocheFR** [comment]
Test done with a 2.2Mo gif. It takes more than 4 seconds to load and it seems that the height/width is expanded. I open it with XnView or with WebBrowser object and it is in fact much smaller in size (at least 4 times I think).
For the Stream, I need to load multiple images in same panel, so I can't really figure to let the gif to load before closing the stream(s).

**Comment by thomaslevesque** [comment]
> it seems that the height/width is expanded

Are you sure it's not the WPF rendering that is stretched? Make sure to set `Stretch="None"` on the `Image` control.

**Comment by ChRocheFR** [comment]
Stretch to none correct the size (thanks for that, I do not know how I missed that), but the loading time is the same.

**Comment by ChRocheFR** [comment]
Upgraded target framework from 4.5.1 to 4.6.1 and seems to be good now for loading. I still have an exception on delete but I will look at my code for any logic error.
Thanks for your work.

**Comment by thomaslevesque** [comment]
Thanks for the update @ChRocheFR. Not sure what could have caused the issue, but I'm glad you were able to resolve it.
