### ISSUE TITLE
Low framerate with only 1 gif showing

### ISSUE THREAD

**Issue by leonardvdj** [XamlAnimatedGif/XamlAnimatedGif#115]
- Application type: WPF 4.5+
- Operating system version: Windows 10 Pro 1803

I'm trying to show [this](https://cdn.betterttv.net/emote/5ada077451d4120ea3918426/1x) gif in my project, but even if I only show a single image control, it runs at about 50% speed. I'm loading it from a MemoryStream. With WpfAnimatedGif it runs full speed, but the memory usage is absolutely crazy, far more than what I believe a 28x28 gif should use.

Is there a way to make XamlAnimatedGif work for my usecase? It's for emotes in a chat client.

**Comment by thomaslevesque** [comment]
Hi @leonardvdj,

It usually works reasonably well with small images like this, but this one has a very high framerate (50 FPS), and apparently it's too much for my library :(
I have a few ideas to make things faster (probably involving a speed vs. memory tradeoff), but to be honest I have no idea when I'll find the time to do it.

**Comment by leonardvdj** [comment]
@thomaslevesque I see, well if you could update me here if progress is made that could be very nice.

**Comment by thomaslevesque** [comment]
Closing in favor of #88
