### ISSUE TITLE
Images and GIFs take forever to even display.

### ISSUE THREAD

**Issue by KyzaGitHub** [XamlAnimatedGif/XamlAnimatedGif#116]
I am adding a mix of images and GIFs to a ListView like so:

XAML
```
<ListView.ItemTemplate>
  <DataTemplate>
    <Image gif:AnimationBehavior.SourceUri="{Binding}" Height="300" Width="300" Margin="4"/>
  </DataTemplate>
</ListView.ItemTemplate>
```

C#
```
var gifImage = new System.Windows.Controls.Image();

AnimationBehavior.SetSourceUri(gifImage, new Uri(file));
AnimationBehavior.SetRepeatBehavior(gifImage, RepeatBehavior.Forever);

ImageViewer.Items.Add(AnimationBehavior.GetSourceUri(gifImage));
```

The images take on average of 5 seconds to load, while the GIFs take up to 5 minutes to load (this being a 55MB one). And all the while the UI is locked up and my CPU is at 100%.

When they finally finish loading, they play slower than usual.

I'm not exactly sure why it is doing this, the WPF is only showing 8 images/GIFs at a time and usually only 1 or no GIFs, only images.

It is also giving large amounts of errors in the console:

```
'MemeManager.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Cannot find or open the PDB file.
'MemeManager.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\USER\source\repos\MemeManager\MemeManager\bin\Release\MemeManager.exe'. Symbols loaded.
'MemeManager.exe' (CLR v4.0.30319: MemeManager.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. Cannot find or open the PDB file.
'MemeManager.exe' (CLR v4.0.30319: MemeManager.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. Cannot find or open the PDB file.
'MemeManager.exe' (CLR v4.0.30319: MemeManager.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Cannot find or open the PDB file.
'MemeManager.exe' (CLR v4.0.30319: MemeManager.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. Cannot find or open the PDB file.
'MemeManager.exe' (CLR v4.0.30319: MemeManager.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Cannot find or open the PDB file.
'MemeManager.exe' (CLR v4.0.30319: MemeManager.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. Cannot find or open the PDB file.
'MemeManager.exe' (CLR v4.0.30319: MemeManager.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Cannot find or open the PDB file.
'MemeManager.exe' (CLR v4.0.30319: MemeManager.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Cannot find or open the PDB file.
'MemeManager.exe' (CLR v4.0.30319: MemeManager.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll'. Cannot find or open the PDB file.
'MemeManager.exe' (CLR v4.0.30319: MemeManager.exe): Loaded 'C:\Users\USER\source\repos\MemeManager\MemeManager\bin\Release\XamlAnimatedGif.dll'. Cannot find or open the PDB file.
'MemeManager.exe' (CLR v4.0.30319: MemeManager.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll'. Cannot find or open the PDB file.
'MemeManager.exe' (CLR v4.0.30319: MemeManager.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll'. Cannot find or open the PDB file.
'MemeManager.exe' (CLR v4.0.30319: MemeManager.exe): Loaded 'C:\Users\USER\AppData\Local\Temp\VisualStudio.XamlDiagnostics.5484\Microsoft.VisualStudio.DesignTools.WpfTap.dll'. Cannot find or open the PDB file.
'MemeManager.exe' (CLR v4.0.30319: MemeManager.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll'. Cannot find or open the PDB file.
'MemeManager.exe' (CLR v4.0.30319: MemeManager.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\SMDiagnostics.dll'. Cannot find or open the PDB file.
'MemeManager.exe' (CLR v4.0.30319: MemeManager.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Internals\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Internals.dll'. Cannot find or open the PDB file.
'MemeManager.exe' (CLR v4.0.30319: MemeManager.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll'. Cannot find or open the PDB file.
Exception thrown: 'XamlAnimatedGif.Decoding.InvalidSignatureException' in XamlAnimatedGif.dll
Exception thrown: 'XamlAnimatedGif.Decoding.InvalidSignatureException' in mscorlib.dll
```

The last two exceptions are repeated randomly. I don't have a slow computer, I tried the old WPFAnimatedGif package and it loaded the GIFs almost instantly. I have to change to this because it absolutely murders my RAM.

**Comment by KyzaGitHub** [comment]
I ended up using `MediaElement` to solve this problem.

**Comment by thomaslevesque** [comment]
> this being a 55MB one

Wow. I didn't even know such large GIFs existed. Shouldn't it be a video instead? I know this library has performance issues, but honestly, 55MB for a GIF is just crazy, I wouldn't expect to be able to play it at a decent speed. How many frames are there? How large are the frames?

As for non-animated images, I guess it could be improved. Currently I try to load the image as a GIF, and if it fails I fallback to loading it as a normal image; maybe it would be possible to detect that earlier and skip GIF decoding. In the meantime, you could set `Source` instead of `gif:AnimationBehavior.SourceUri` when the image is not a GIF.

**Comment by KyzaGitHub** [comment]
I have a 93MB one but I haven't tried loading it yet. As for the 55MB one, it's 633x356 and has 570 frames.

About setting `Source` instead of `gif:AnimationBehavior.SourceUri`, this is my first WPF project and I don't have any idea how I would do this with `{Binding}`. I've tried looking up documentation on it but I've had no luck. Maybe I should be taking a different approach to this? I want to make sure I can keep the size of the images 300x300 where 300px is the largest of width or height if the aspect ratio isn't 1:1.

**Comment by thomaslevesque** [comment]
> I have a 93MB one but I haven't tried loading it yet. As for the 55MB one, it's 633x356 and has 570 frames.

Well, at 570 frames, it should probably be a video, not a GIF... I'm not sure I could make it render faster. Is this an image you'd be able to share so I can see what's taking so long?

> About setting `Source` instead of `gif:AnimationBehavior.SourceUri`, this is my first WPF project and I don't have any idea how I would do this with `{Binding}`

If you do it with binding, you can bind `Source` and `gif:AnimationBehavior.SourceUri` to different properties:

```xml
<Image gif:AnimationBehavior.SourceUri="{Binding GifUri}" Source="{Binding NonGifUri}" />
```
and set `GifUri` or `NonGifUri` depending on the image you want to display.

In code behind, you can use `image.Source = ...` instead of `AnimationBehavior.SetSourceUri(image, ...)`. However it requires loading the image yourself (`Source` doesn't accept a URI directly):

```C#
var img = new BitmapImage();
img.BeginInit();
img.UriSource = ...
img.EndInit();
image.Source = img;
```

**Comment by thomaslevesque** [comment]
Closing as "won't fix". I don't expect XamlAnimatedGif to ever be able to play such a large ~~video~~gif at normal speed.
I do have plans to improve performance, but honestly I lack the time and motivation to maintain this project, so I don't know if or when I'll do it.
