### ISSUE TITLE
VS 2017, .NET 4.7 - Exception on XAML Parsing

### ISSUE THREAD

**Issue by dpotts-sc** [XamlAnimatedGif/XamlAnimatedGif#128]
- WPF .NET 4.7 using Visual Studio 2017 -- Windows 10

* I have installed via NuGet
* setup the XAML to point to the image I want animated
* When I load the Window with the animated GIF at the "InitializeComponent()" call in the constructor for the window, I get the following exception :
'Could not load file or assembly 'XamlAnimatedGif, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.'

I have tried point directly to an animated GIF file, no difference.  (This works with MediaElement) :(   Ideally I want it working with a embedded resource, but for now I'd like it to work at all. 

Problem has returned when using the WPF version directly and not installed via-NuGet.  :(

Any thoughts?

**Comment by dpotts-sc** [comment]
Not sure what happened, but I uninstalled the XamlAnimatedGif and re-installed and now everything is working?  Everything through NuGet, so I'm confused.

**Comment by dpotts-sc** [comment]
NOTE : The solution is to make sure that all projects and sub-projects have a reference to the XamlAnimatedGif.Wpf project.  This was the problem, cleaned it up and it works now.

**Comment by thomaslevesque** [comment]
> Ideally I want it working with a embedded resource

It should work with no additional work, exactly as it works for a normal image.

Since you have resolved your problem, I'll close the issue.
