### ISSUE TITLE
"A task was canceled" exception on Dispose

### ISSUE THREAD

**Issue by faze79** [XamlAnimatedGif/XamlAnimatedGif#130]
- Application type: WPF 4.5+ 
- Operating system version: Windows 10
- Expected behavior: Not throw exception
- Actual behavior: throw exception on Dispose() of Animator
- Steps to reproduce the problem: Show Hide a window with a gif many times.

I think in TimingManager.NextAsync you have simply to check for CancellationTokenSource.IsCancellationRequested so the execution is interrupted correctly.
Here is also my callstack for this error:
 	

mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task) + 0xae bytes	
 	mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task) + 0x41 bytes	
 	mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.GetResult() + 0x1c bytes	
 	XamlAnimatedGif.dll!XamlAnimatedGif.TimingManager.NextAsync() + 0x314 bytes	
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine) + 0x1a bytes	
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) + 0xc4 bytes	
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) + 0x17 bytes	
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() + 0x5e bytes	
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.InvokeAction(object state) + 0x2c bytes	
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback callback, object state, ref System.Threading.Tasks.Task currentTask = null) + 0x56 bytes	
 	mscorlib.dll!System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run(System.Threading.Tasks.Task task, bool canInlineContinuationTask) + 0x129 bytes	
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations() + 0x47d bytes	
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree() + 0x1a bytes	
 	mscorlib.dll!System.Threading.Tasks.Task.CancellationCleanupLogic() + 0x72 bytes	
 	mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetCanceled(System.Threading.CancellationToken tokenToRecord, object cancellationException) + 0x46 bytes	
 	mscorlib.dll!System.Threading.Tasks.Task.DelayPromise.Complete() + 0xa6 bytes	
 	mscorlib.dll!System.Threading.Tasks.Task.Delay.AnonymousMethod__274_0(object state) + 0x2a bytes	
 	mscorlib.dll!System.Threading.CancellationCallbackInfo.ExecutionContextCallback(object obj) + 0x20 bytes	
 	mscorlib.dll!System.Threading.CancellationCallbackInfo.ExecuteCallback() + 0x2a bytes	
 	mscorlib.dll!System.Threading.CancellationTokenSource.CancellationCallbackCoreWork(System.Threading.CancellationCallbackCoreWorkArguments args) + 0x2d bytes	
 	mscorlib.dll!System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(bool throwOnFirstException = false) + 0xf7 bytes	
 	mscorlib.dll!System.Threading.CancellationTokenSource.NotifyCancellation(bool throwOnFirstException) + 0x54 bytes	
 	mscorlib.dll!System.Threading.CancellationTokenSource.Cancel() + 0x1d bytes	
 	XamlAnimatedGif.dll!XamlAnimatedGif.Animator.Dispose(bool disposing = true) + 0x9e bytes	
 	XamlAnimatedGif.dll!XamlAnimatedGif.Animator.Dispose() + 0x25 bytes	
 	XamlAnimatedGif.dll!XamlAnimatedGif.AnimationBehavior.ClearAnimatorCore(System.Windows.Controls.Image image = {System.Windows.Controls.Image}) + 0xae bytes	
 	XamlAnimatedGif.dll!XamlAnimatedGif.AnimationBehavior.InitAnimation(System.Windows.Controls.Image image = {System.Windows.Controls.Image}) + 0xf2 bytes	
 	XamlAnimatedGif.dll!XamlAnimatedGif.AnimationBehavior.Image_Loaded(object sender = {System.Windows.Controls.Image}, System.Windows.RoutedEventArgs e = {System.Windows.RoutedEventArgs}) + 0x84 bytes

**Comment by thomaslevesque** [comment]
Hi @faze79,
Thanks for the report, I'll look into it

**Comment by thomaslevesque** [comment]
Hi @faze69,

I haven't been able to reproduce the problem, but I think I know what's causing it.
I published a beta that should fix it, could you try it please?

**Comment by thomaslevesque** [comment]
@faze79 have you been able to try the beta? Please keep me posted, if it works as expected I'll publish a stable release.

**Comment by thomaslevesque** [comment]
@faze79 I didn't get any feedback from you, so I'll assume the issue is fixed. Please chime in if you still encounter the problem.

I just released [1.2.2](https://github.com/XamlAnimatedGif/XamlAnimatedGif/releases/tag/1.2.2) which includes the fix.
