### ISSUE TITLE
Provide a strong named version. 

### ISSUE THREAD

**Issue by SchreinerK** [XamlAnimatedGif/XamlAnimatedGif#133]
```
Referenced assembly 'XamlAnimatedGif, Version=1.2.2.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```

To reference this assembly from an assembly with strong name, this assembly must also have a strong name.

**Comment by thomaslevesque** [comment]
Adding a strong name is a breaking change, so I'll do it in the next major release.
But to be honest, I don't know when that will be... In the meantime, I suggestion you use [this package](https://www.nuget.org/packages/Brutal.Dev.StrongNameSigner/) to strongly sign the assembly yourself at build time.

**Comment by SchreinerK** [comment]
Thanks. Interesting tool, I will have a look on it. In the meantime I have forked your repository and signed the WPF part only. Because I only use GIF in an optional sample plugin for my converter and anybody can create own plugin, is this an acceptable temporary solution  for me. In the future it would be nice, when your nuget package could be used directly.

**Comment by thomaslevesque** [comment]
v2 is coming soon, with a strongly-named assembly
