### ISSUE TITLE
How can i solve memory leak?

### ISSUE THREAD

**Issue by neosherif** [XamlAnimatedGif/XamlAnimatedGif#135]
# If you're reporting a bug, please fill in the following information, otherwise delete this section

- Application type: WPF 4.5+ 
- Operating system version: Windows 10
- Expected behavior: Memory Release
- Actual behavior: Memory Increase
- Steps to reproduce the problem:
  1. Page2 button click
  2. Page1 button click
  3. Repeat operation 1 and 2 times
  4. The memory only increases, not decreases.
  5. It does not increase when switching between pages 2 and 3

- If you're having issues with a specific GIF file, please attach or link the file.
  This is sample.
  My real program does not display an image after switching several pages.
[WpfApplication1.zip](https://github.com/XamlAnimatedGif/XamlAnimatedGif/files/4142160/WpfApplication1.zip)

**Comment by thomaslevesque** [comment]
Hi @neosherif,

How did you measure the memory usage? The Windows Task Manager isn't a very good tool for that, you should use a profiler. Does the app keep using more memory until it crashes?
Is the memory released if you trigger garbage collection? (calling `GC.Collect()`)
If it is released, it's not a leak; garbage collection runs only when it needs to.

I ran the app through the Visual Studio profiler, and it didn't show a significant difference in memory usage between snapshots:

![image](https://user-images.githubusercontent.com/1864281/73590891-4b9e7a00-44e8-11ea-847d-0c2374d16703.png)

As you can see, it releases a bit of memory when I switch to page 2, and takes a bit more when I switch to page 1 (about the same amount, which is consistent). So as far as I can tell, there's no leak...

**Comment by neosherif** [comment]
Ok. Thank you and sorry
I have confirmed that there is no memory leak.
I see that the memory is increased because of the page object.

**Comment by thomaslevesque** [comment]
You're welcome!
