### ISSUE TITLE
Build with config x64 not working

### ISSUE THREAD

**Issue by alexandrejournet** [XamlAnimatedGif/XamlAnimatedGif#136]
- Application type: WPF 4.0
- Operating system version: Windows 10
- Expected behavior: Show Gif
- Actual behavior: Not showing gif in 64bits, in a config x86, it works
- Steps to reproduce the problem:
  1. Just put the config to x64

**Comment by thomaslevesque** [comment]
Hi @alexandrejournet,

I just tried it, and it works fine for me... Could you please send a project that reproduces the issue?
Or maybe it's specific to the GIF image you're using; could you send it to me so that I can investigate?

**Comment by alexandrejournet** [comment]
https://github.com/alexandrejournet/TestGifWPF

I tested with two differents gif and same problem, just switch between x64 and x86 config, not AnyCPU. Even in design mode it's not working ^^

**Comment by thomaslevesque** [comment]
Hi @alexandrejournet,

I just tried your project. It works fine for me, whether in x86 or x64. Have you tried on a different machine? The problem might be related to your machine...

**Comment by alexandrejournet** [comment]
Hi @thomaslevesque,

I'm going to try on another machine and I come back to you !

**Comment by alexandrejournet** [comment]
@thomaslevesque,
This works on my other machine, I'll just try again on my main machine, sorry for this issue ! ^^

**Comment by thomaslevesque** [comment]
Thanks for checking. It would be interesting to know what the problem was; can you see an error if you subscribe to the `AnimationBehavior.Error` event?
