### ISSUE TITLE
Support for .NET Core 3.1

### ISSUE THREAD

**Issue by tensei** [XamlAnimatedGif/XamlAnimatedGif#137]

**Comment by thomaslevesque** [comment]
Hi tensei,

Thanks for the suggestion. It's been on my mind for a while, but I haven't got around to do it yet.

**Comment by thomaslevesque** [comment]
v2 is coming soon, with .NET Core 3.1 and .NET 5.0 support

**Comment by thomaslevesque** [comment]
I just released 2.0.0-alpha.1. Please let me know if you run into issues with it!
