### ISSUE TITLE
Changing value of SourceUri uses a little bit more memory each time

### ISSUE THREAD

**Issue by Jicol95** [XamlAnimatedGif/XamlAnimatedGif#138]
- Application type: WPF 4.0 
- Expected behaviour: Loading the gif should use the same amount of memory (roughly) each time when loading the same image.
- Actual behaviour: When reassigning the source URI it seems to claim slightly more memory each time.
- Steps to reproduce the problem:
  1. Set resource URI to null
  2. Navigate away
  3. Navigate to
  4. Set resource URI to GIF

**Comment by thomaslevesque** [comment]
Hi @Jicol95,

How are you measuring memory usage? If you're just looking at the Task Manager, it doesn't really mean anything, since it doesn't account for garbage collection. The proper way to check if memory is leaking is to use a memory profiler.

Does the memory usage go back down when you call `GC.Collect()`?

**Comment by Jicol95** [comment]
Thanks for the quick response.

I have used both ANTS memory profiler and diagnostic tools to measure the memory usage.

So I have tried GC.Collect() after setting SourceUri to null which does release the memory. However if I reload the image it loads back with more memory than before. So when I'm not using that image everything is fine, but can jump from around 400MB memory to 2GB when loading this image if I do it enough times.

![Profiler](https://user-images.githubusercontent.com/19427656/89401554-5e02a600-d70d-11ea-9e2d-b067506446a6.PNG)

As you can see it always returns to a reasonable amount after GC.Collect() but seems to grow beyond the initial value when reloading.

**Comment by thomaslevesque** [comment]
That's weird... If it goes back to normal after a GC.Collect, there shouldn't be a leak. I'm not sure what could cause the memory usage to increase like that the next time you load an image.

Can you see if new objects are retained between snapshots?
Are you able to reproduce the problem in a simple standalone project?

**Comment by Jicol95** [comment]
Struggled to find retained objects using ANTS profiler. In honesty my strategy is a bit all over the place as I'm fairly new to ANTS.

Here's the problem reproduced in a simpler project https://github.com/Jicol95/AnimatedGifIssue just navigate back and forward to see what I've been talking about.

Apologies this took me longer than I wanted it to. Let me know if there are any issues with the project I have provided.

**Comment by thomaslevesque** [comment]
Thanks! I'll try to reproduce it on my side

**Comment by thomaslevesque** [comment]
I'm able to reproduce the issue using Visual Studio's built-in profiler

![image](https://user-images.githubusercontent.com/1864281/89663708-3f034000-d8d6-11ea-9ad6-a05b7e191de1.png)

The memory usage graph clearly shows that it's using more memory every time the GIF is displayed. However, the diffs between snapshot don't reflect that: sometimes more memory is used, sometimes some memory is freed...
So I'm not sure yet what's going on, but there's definitely something fishy. I'll have to dive into the code.

**Comment by thomaslevesque** [comment]
OK, I have a lead...

I added a Debug.WriteLine where the ImageAnimator is created. The first time I navigate to the payment page, the debug line appears once. The next time, it appears 4 times. The next time, it appears 7 times. The next time, 10 times. And so on...
So it's getting slower and slower, and uses more memory every time.

I'm not sure yet what's causing this, but at least I have an idea what to look for.

**Comment by thomaslevesque** [comment]
OK, found it. I was subscribing to the image `Loaded` event more often than I was unsubscribing. This caused the handler to be caused multiple times, causing the animation to be created too often.
I'll release a fix ASAP

**Comment by thomaslevesque** [comment]
I just released [1.2.3](https://github.com/XamlAnimatedGif/XamlAnimatedGif/releases/tag/1.2.3) with the fix.
Thanks @Jicol95 for reporting this issue, and for providing a good repro!

**Comment by Jicol95** [comment]
Thank you @thomaslevesque for fixing this so quickly!
