### ISSUE TITLE
Dialog problem on "dialogWindow.Show()"

### ISSUE THREAD

**Issue by steffy97** [XamlAnimatedGif/XamlAnimatedGif#141]
- Application type: WPF 4.0 +
- Operating system version: Windows
- Expected behavior: The animated .gif normally animate.
- Actual behavior: Not animated on dialog.Show(), but work with dialog.ShowDialog()
- Steps to reproduce the problem: Create a second Window form with a animate gif and open this window from the main window with "Show()" method. The .gif will not animate.
  I use this window like a warning and he close automatically after another methode. Its the reason why I don't use Showdialog().
- If you're having issues with a specific GIF file, please attach or link the file.
![Dual_Ball](https://user-images.githubusercontent.com/23193151/89917818-41f87c00-dbc7-11ea-8533-d76694e3fcae.gif)

Great job and thank you!

**Comment by thomaslevesque** [comment]
Hi @steffy97,

Interesting... I'm not sure what could be causing this. I'll have a look.

**Comment by thomaslevesque** [comment]
Hi @steffy97,

I'm unable to reproduce the issue. Are you able to reproduce it in a minimal project (with just the main window and the dialog)?

**Comment by steffy97** [comment]
.... I tried, but its worked... I do probably something in my real project who probably block the main UI Thread. The reason why the showdialog work, its probably because this block the thread. The close() action send me on a bad way... Still, I searched for hours before imagining it was a bug. I am very new to WPF. I'm really sorry.  Your project is awesome.

**Comment by thomaslevesque** [comment]
Don't be sorry, it could totally have been a bug in the library (it still could, actually!)
Feel free to reopen this issue if necessary

**Comment by steffy97** [comment]
Thank you!
