### ISSUE TITLE
Gif in comboBox template was not valid

### ISSUE THREAD

**Issue by chancezheng** [XamlAnimatedGif/XamlAnimatedGif#150]
When I was rewrite ComboBox control, I place a <Image/> control which I try to make it gif in ComboBoxItem,
But the drop list of ComboBox was not open,however only alone Image control is ok,

**Comment by thomaslevesque** [comment]
Hi @chancezheng,

I'm sorry, I don't understand your problem. Could you try to explain it better?

**Comment by chancezheng** [comment]
![bug](https://user-images.githubusercontent.com/31839078/112301622-18fba600-8cd5-11eb-9d8b-06bb1b9ae451.png)
such as this comboxbox control,I try to change the image into gif of comboboxitem  control, but it does't work well, however only alone Image control is ok

**Comment by thomaslevesque** [comment]
> it does't work well

Could you be more specific? Also, please show the relevant code.
