### ISSUE TITLE
When installed via Nuget Package on Net 5 (Core), it will be restored to NetFramework.

### ISSUE THREAD

**Issue by SID9-HoneyBee** [XamlAnimatedGif/XamlAnimatedGif#151]
Net 5 (core) / WPF / C#
This is the Visual Studio 2019 environment.

If you install through Nuget Package like the attached image,
Net Framework is restored.

Should I download the source and use it after compiling with Net5?

![image](https://user-images.githubusercontent.com/76090330/119748580-28af8a80-bed0-11eb-8a10-d90ca50d6351.png)

Additionally,
788kb gif file was called.
(800*600)

I set it to start automatically, but it takes a long time for GIF to run and move.

How should I do it?

**Comment by thomaslevesque** [comment]
Hi @SID9-HoneyBee,

That's because the current stable version doesn't target .NET Core / .NET 5. There's an 2.0.0-alpha.1 version that targets .NET Core 3.1. I will release a new stable version soon (with a .NET 5 target)

**Comment by thomaslevesque** [comment]
> I set it to start automatically, but it takes a long time for GIF to run and move.

About that: yes, it's a known problem. The library doesn't perform well for large GIFs. I have plans to improve this, but to be honest, I don't have a lot of time to maintain this library, so I don't know if or when I will get around to do it...

**Comment by thomaslevesque** [comment]
Hi @SID9-HoneyBee,

I just published version 2.0.0, which targets .NET 5. This should solve your problem.
