### ISSUE TITLE
Some gif cannot display correctly

### ISSUE THREAD

**Issue by penny681028** [XamlAnimatedGif/XamlAnimatedGif#157]
**Describe the bug**
Some Gif cannot display correctly

**To Reproduce**
Assign the gif path to display

**Expected behavior**
some area looks like transparent

**Screenshots**
Fail
![image](https://user-images.githubusercontent.com/23231330/131083332-719f3729-1655-4c5f-b97b-ffa84ca41e89.png)
Pass
![image](https://user-images.githubusercontent.com/23231330/131083409-f4021eb1-53a5-448a-a545-4d95d5dbcbd2.png)

**Please complete the following information:**
- Application type: WPF 4.5+
- Operating system version: Windows 10
![trump_hateSpeech](https://user-images.githubusercontent.com/23231330/131083483-ff2dee54-70da-4af3-bf8f-3eb4e37fe8ea.gif)

**Additional context**
It's ok with browser or other gif library.

**Comment by penny681028** [comment]
The fail file download from https://i1.wp.com/dedipic.com/wp-content/uploads/2019/01/trump_hateSpeech.gif?resize=500%2c500&ssl=1, seems the pic resize by some tool. If we download from https://i1.wp.com/dedipic.com/wp-content/uploads/2019/01/trump_hateSpeech.gif, the GIF is ok.

**Comment by thomaslevesque** [comment]
@penny681028 interesting... So it *is* wordpress. Looks like the resizing process completely reencodes the image, and while doing so, introduces this issue.
