### ISSUE TITLE
Intel(R) UHD Graphics显卡无法正常播放

### ISSUE THREAD

**Issue by qian-o** [XamlAnimatedGif/XamlAnimatedGif#159]
测试环境：
       处理器：11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
       系统：Windows 11 专业版 21H2 22000.194
       Microsoft Visual Studio Community 2019 版本 16.11.3
拉取XamlAnimatedGif代码后运行XamlAnimatedGif.Demo播放GIF时报错
设置为自动选择时，无法正常播放只显示第一帧
![image](https://user-images.githubusercontent.com/84434846/134460179-9ce7a8fd-e70f-4a64-9347-788579398d50.png)
设置为高性能NVIDIA处理器可以流畅运行
![image](https://user-images.githubusercontent.com/84434846/134460218-5d121678-b9be-47fa-b024-01068423542e.png)

**Comment by thomaslevesque** [comment]
Hi @qian-o,
Sorry, I don't understand Chinese. I'll be glad to try to help you if you open a new issue in English.
