### ISSUE TITLE
Animation plays one frame then stops

### ISSUE THREAD

**Issue by egauthierphy** [XamlAnimatedGif/XamlAnimatedGif#161]
Only on a new Microsoft Surface Pro 7+, the first frame of the GIF is displayed but the next are not shown.

I created a small WPF application that only displays a 4 frame GIF.

![numbers-animated](https://user-images.githubusercontent.com/36052122/134713774-51b858db-36ad-437c-adf8-d65b6d47388b.gif)

I'm using VStudio 2019 (16.10.4), targeting .NET 5. The PCs I tested on are all various builds of Windows 10 running .NET Desktop Runtime 5.0.10. All play fine but the Surface Pro 7+.

Hypothesis: the newest Surface sports the new 11th gen Intel Mobile CPU line (i5-1135G7). This is the only thing that stands out of the other PCs I tested on (both laptops and desktop). I also tested on the earlier 10th gen Mobile CPU and it works.

Maybe it is related to the video driver?
![image](https://user-images.githubusercontent.com/36052122/134713712-29a1b8c5-d2a1-4291-a9f1-fb0c55aee98c.png)

There is a closed issue that seems related: #159

I will try to debug it with the source code, but did you see reports of this?

**Comment by egauthierphy** [comment]
This was a graphics driver issue: https://github.com/dotnet/wpf/issues/3817

Fixed by upgrading the driver to the latest version (30.0.100.9864).

**Comment by thomaslevesque** [comment]
Hi @egauthierphy,

Glad you were able to solve this!
