### ISSUE TITLE
SetSourceStream dont work?

### ISSUE THREAD

**Issue by vvyoko** [XamlAnimatedGif/XamlAnimatedGif#168]
**Please complete the following information:**
- Application type:  WPF 4.0 / WPF 4.5+
- Operating system version: WIN10 19044

**Additional context**
The path contains the `Uri ` of certain characters, there will be errors
see https://github.com/dotnet/runtime/issues/27399

So I want to use `SetSourceStream `
But when I refer to the example, it cannot work
Whether it contains the path of special characters, or the normal path

example:
https://github.com/XamlAnimatedGif/XamlAnimatedGif/blob/9f373cd7c203c338f963aeb2df8acd2e0a2a5ecb/XamlAnimatedGif.Demo/BasicTestsWindow.xaml.cs#L58

Very simple test

```
string path = @"D:\3~(A@C5RX})Y5@F%2EZ(@I9.gif";
MessageBox.Show($"{File.Exists(new Uri(path).LocalPath)}");  // false 

//AnimationBehavior.SetSourceUri(image, new Uri(path));  // so cant use that

using (var fileStream = File.OpenRead(path))
{
    AnimationBehavior.SetSourceStream(image, fileStream); // cant work
}

// AnimationBehavior.SetSourceUri(image, new Uri("D:\\123.gif"));  //same file rename  can work
```

**Comment by thomaslevesque** [comment]
Hi @vvyoko,

I think this is because the stream is disposed immediately after you assign it (at the end of the `using` block). It needs to remain open as long as you're showing the animation. In the example, it works because the stream isn't disposed until after the window is closed.
