### ISSUE TITLE
Manually using the animator.  Calling Pause() Twice causes animation to not resume when calling Resume();

### ISSUE THREAD

**Issue by Teravus** [XamlAnimatedGif/XamlAnimatedGif#170]
**Describe the bug**
If I pause the animation twice with the animation controller, the animation will not resume when I call Resume()

I have an animated image gif that I'm using as a cursor.   When the user moves the mouse over something that would trigger a response if they clicked, I call pause on the animator.  When the mouse is not over something, I resume the animation.
I found that once I paused the animation by rolling the mouse over something, I could call resume when I roll off of it and it wouldn't play.

```csharp
this.MouseMove += (s, e) =>
{
    bool overhotspot = _mainScenePlayer.MouseClick(relclickX, relclickY, false);
    if (overhotspot)
    {
         Spinner.Stop(); // Hooked to _animator.Pause();
    }
    else
    {
       Spinner.Start(); // Hooked to _animator.Resume();
    }
};
```
For the purposes of testing, I hooked up Spinner.Start() and Spinner.Stop() to keys Y and U...  and found that when I pressed the button that I hooked to pause the animation....   twice.   Clicking the button hooked to Resume() wouldn't resume the animation.

I put a breakpoint in Animator.cs RunAsync and found that it wasn't firing when the problem occurs.

I feel like this might be some kind of reference issue in the _pauseCompletionSource in TimingManager.   Before replacing _pauseCompletionSource with a new TaskCompletionSource, it might make sense to set result on the last one, or throw an exception.

**To Reproduce**
Make a simple manual animation controller (based on the example template in this repository) that hooks to AnimationBehavior.AddLoadedHandler(boundControl,  Method_OnAnimationLoaded);
Grab the animator _animator = AnimationBehavior.GetAnimator(BoundControl);
Call _animator.Pause();
Call _animator.Pause(); again
Call _animator.Play();

Animation will not resume.

**Expected behavior**
Animation resumes when you call _animator.Play();   OR an exception is thrown when you call _animator.Pause(); for the second time.

**Please complete the following information:**
- .NET version: .NET Framework 4.7.2
- Operating system version: Windows 11
- If you're having issues with a specific GIF file, please attach or link the file:  Not specific to Gif.

**Additional context**
I'll do a pull request on the first of the expected behavior; _animator.Play(); resumes animation even if you have paused it twice. 

Sure, I can implement a Boolean, or check _animator.IsPaused first to know if the animation is already paused, however, the documentation isn't clear enough to know that you must do that and calling a double Pause would break the threading model.  

When it doesn't work, it's really tough for someone figure out why calling resume isn't working.  I just assumed that it was buggy for several months and tried to use it as little as possible. 

There isn't any message or other notification that you broke it. 

Furthermore, in other frameworks, if you call pause twice or resume twice, the result is it pauses or resumes respectively.  The double action is a no-op.

**Comment by thomaslevesque** [comment]
Thanks @Teravus for reporting and fixing this! I just released [2.0.3](https://github.com/XamlAnimatedGif/XamlAnimatedGif/releases/tag/2.0.3).
