### ISSUE TITLE
Add a property to opt-in for cache to improve performance

### ISSUE THREAD

**Issue by meaysam** [XamlAnimatedGif/XamlAnimatedGif#174]
Adding a few gifs to UI can slow down the UI or make it not responsive.
I want to suggest to add a property to choose caching frame bytes instead of recalculating them every time. This cache could happen before or after decompression. So, I think such a property can have three values "None", "CacheCompressed", "Cache". None would be current behavior. CacheCompressed would be to cache values after frame data is read. Cache would be after frame data is read and also decompressed.

In Animator.RenderFrameAsync method. the result of call to GetIndexStreamAsync call be cached and reused. But perhaps the GetIndexStreamAsync method also needs to be refactored into two different methods for reading frame data and decompressing the frame data.

**Comment by thomaslevesque** [comment]
Hi @meayseam,

Thanks for the suggestion!

Actually, not keeping the frames in memory was one of the design goals of this library, to avoid the memory usage issues that users of [WpfAnimatedGif](https://github.com/XamlAnimatedGif/WpfAnimatedGif) ran into. But I realize it's not always the right thing to do, and in some scenarios, having good performance is more important than keeping memory usage low.

To be honest, I don't really have time to maintain this library anymore. Would you be interested in working on this?

**Comment by thomaslevesque** [comment]
Closed by #175 
Thanks again, @meaysam!
I published a [new release](https://github.com/XamlAnimatedGif/XamlAnimatedGif/releases/tag/2.1.0)
