### ISSUE TITLE
Do not support .NET6

### ISSUE THREAD

**Issue by Ori1993** [XamlAnimatedGif/XamlAnimatedGif#180]
This plugin is not available for .net6  WPF

**Comment by thomaslevesque** [comment]
What do you mean?
It targets `net5.0-windows`, which is compatible with `net6.0-windows`

**Comment by Ori1993** [comment]
> What do you mean? It targets `net5.0-windows`, which is compatible with `net6.0-windows`

> What do you mean? It targets `net5.0-windows`, which is compatible with `net6.0-windows`

Thanks, I have solved this problem when I create WPF project with.netcore3.1 and then switch to.net6

Version it's normal

**Comment by Ori1993** [comment]
> What do you mean? It targets `net5.0-windows`, which is compatible with `net6.0-windows`
Thanks, I have solved this problem when I create WPF project with.netcore3.1 and then switch to.net6
Version it's normal
