### ISSUE TITLE
The GIF's rendered size is incorrect

### ISSUE THREAD

**Issue by Venom1991** [XamlAnimatedGif/XamlAnimatedGif#191]
**Describe the bug**
The GIF is not being rendered in the correct size. The only time in which its size is correct is while resizing the window.

**To Reproduce**
Use the following XAML (for MainWindow) and also the attached GIF:

```
<Window x:Class="XamlGifTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:XamlGifTest"
        xmlns:gif="https://github.com/XamlAnimatedGif/XamlAnimatedGif"
        mc:Ignorable="d"
        Title="GIF Test" Height="450" Width="800">
    <Grid>
        <Image Stretch="None"
	       gif:AnimationBehavior.SourceUri="/XamlGifTest;component/Resources/loader.gif"
               gif:AnimationBehavior.CacheFramesInMemory="True" />
    </Grid>
</Window>
```
![loader](https://github.com/XamlAnimatedGif/XamlAnimatedGif/assets/5722469/e2c69e8a-c899-422b-bc2f-2d5463bcff28)

And run the code, of course.

**Expected behavior**
The GIF should be rendered in the desired size at all times, not just while resizing the window.

**Screenshots**
I've attached a video, instead.

https://github.com/XamlAnimatedGif/XamlAnimatedGif/assets/5722469/7f66293e-dfbd-4996-9bea-823a91ff3b6c

**Please complete the following information:**
- .NET version: 8 (net8.0-windows)
- Operating system version: Windows 10 (Build 19045.3996)

Am I doing something wrong here?

EDIT: The demo app renders the same GIF just fine. I've no idea what's happening.

**Comment by Venom1991** [comment]
Hm, it works fine when I put it inside a GroupBox element, just like in the demo app but I don't really need that in my case. With what should I wrap it to achieve the same behavior?

**Comment by thomaslevesque** [comment]
Hi @Venom1991,

I just tried your original code. It works fine for me...

> Hm, it works fine when I put it inside a GroupBox element, just like in the demo app but I don't really need that in my case. With what should I wrap it to achieve the same behavior?

You could try with a `Border` with BorderThickness=0. But the thing is, you shouldn't need this workaround... Not sure what's going on, but I can't reproduce the issue on my side.

Do you have non-default display scaling enabled in Windows? Or a high DPI screen?

**Comment by Venom1991** [comment]
My display setup:

- internal laptop's monitor (1080p, 144 Hz, scaled to 125%), screen rendered by Intel UHD 630
- external monitor (connected via HDMI, 1080p, 60 Hz, no scaling), screen rendered by NVIDIA GTX 1660 Ti

Latest available drivers are installed for both GPUs and the glitch happens on both monitors so I'm not sure it has anything to do with the graphics HW or SW. I've not been experiencing these glitches in other software or if have been I surely didn't notice any.

**Comment by Venom1991** [comment]
So, I finally figured out the [culprit](https://github.com/dotnet/wpf/issues/2493#issuecomment-588330142). What an unbelievable piece of junk that thing is.
The problem had nothing to do with this library and you can close this issue but I would recommend that you put an explanation in the readme that certain graphical glitches (such as this one) could be caused by Nahimic's software.

**Comment by thomaslevesque** [comment]
That's weird. Nahimic is audio software, I don't understand how it can affect rendering 🤔
Anyway, glad you were able to figure it out!

**Comment by Venom1991** [comment]
> That's weird. Nahimic is audio software, I don't understand how it can affect rendering 🤔 Anyway, glad you were able to figure it out!

Quote from the link I've provided:

> This isn't a WPF issue but an issue with Nahimic's software. They are trapping certain calls and this is interfering with WPF rendering.
