### ISSUE TITLE
Interlaced Gifs do not render correctly on 2.2.x releases

### ISSUE THREAD

**Issue by julianxhokaxhiu** [XamlAnimatedGif/XamlAnimatedGif#193]
**Describe the bug**

Hello, we've been using this library since a long time on our own project https://github.com/tsunamods-codes/7th-Heaven and we've been very happy with it!

Unfortunately though since we migrated it to .NET 8 we found out that this library is rendering some Gifs completely broken, here a screenshot of how it looks like on the Demo ( I cloned the project and built it on top of `net8.0-windows7.0` ):

![image](https://github.com/XamlAnimatedGif/XamlAnimatedGif/assets/1237070/4397fe1f-8b01-42d3-bc32-06bbae113dbe)

Any idea what might be the cause? Thank you in advance!

**To Reproduce**

1. Build the project using latest `master` and `net8.0-windows7.0` as target framework
2. Launch the Demo app
3. Load this gif file: [preview.zip](https://github.com/XamlAnimatedGif/XamlAnimatedGif/files/14251001/preview.zip) ( rename to `.7z` to unpack it )

**Expected behavior**

The gif shows up just fine.

**Screenshots**

See above.

**Please complete the following information:**
- .NET version: 8.0.1
- Operating system version: Windows 11
- If you're having issues with a specific GIF file, please attach or link the file: See above

**Additional context**

N/A

**Comment by thomaslevesque** [comment]
Hi @julianxhokaxhiu,

Thanks for reporting this. I don't think it's specific to .NET 8, I can also reproduce the issue on .NET Framework.

The way it looks makes me think the problem is related to interlacing. It's as if the image data is interlaced, but the interlace bit is not set, so we decode the image data as if it were not interlaced. Other apps have no trouble rendering the image, though... I'll need to look into it in more detail, when I have the time.

**Comment by julianxhokaxhiu** [comment]
Hey @thomaslevesque thanks a lot for the reply! Now that at least I have a lead I might try to look at the code and see if I can spot anything. I'll let you know if I may find out what is going on. Thanks!

**Comment by thomaslevesque** [comment]
OK, I think there's a bug in here somewhere... The image data is [interlaced](https://en.wikipedia.org/wiki/GIF#Interlacing), _and_ the interlace bit is properly set, but the library isn't rendering the lines in the correct order. I'll need to dive into the rendering code to understand what's going on.

**Comment by thomaslevesque** [comment]
Oh, I missed your previous message! reading it now

**Comment by thomaslevesque** [comment]
I don't want to just revert that commit, though... I'll try to figure out what broke interlacing exactly.

**Comment by thomaslevesque** [comment]
I fixed the issue. Would you happen to have a smaller GIF that also exhibit the issue? I'd like to add it to the demo project to be able to check there's no regression.

**Comment by thomaslevesque** [comment]
Version 2.2.2 is published and should appear on NuGet shortly

**Comment by julianxhokaxhiu** [comment]
Thanks a lot for quickly fixing this! I can confirm the issue is now fixed when using 2.2.2 :)

I was reported also another GIF that was having this issue. I'll upload it as soon as I get my hands on it.

**Comment by julianxhokaxhiu** [comment]
There you go, this was the other gif. It's part of another mod we managed on the Final Fantasy community. If it helps for your testings you're welcome to use it. Thanks again!

[Phoenix_Tail_II_Mod.zip](https://github.com/XamlAnimatedGif/XamlAnimatedGif/files/14272242/Phoenix_Tail_II_Mod.zip)

**Comment by thomaslevesque** [comment]
Thanks!
