### ISSUE TITLE
Any issues with VS2015 crashing w/ UWP app?

### ISSUE THREAD

**Issue by Xiard** [XamlAnimatedGif/XamlAnimatedGif#32]
Have you seen any issues with VS2015 freezing when using XmlAnimatedGif?  I just installed the package today, and VS either freezes trying to run my app, or freezes when I shut the app down after it launches.  It's a big project, and VS2015 isn't rock solid, so who knows if this has anything to do with your package.  But it did start happening after I installed it.  Going to try uninstalling it and seeing what happens.

This is a UWP app, btw, and I'm running Win10 10240 (not on the fast ring for this PC at the moment).

**Comment by thomaslevesque** [comment]
No, I haven't noticed anything like that. However I haven't used XamlAnimatedGif a lot recently, and I have barely tried it in a UWP app, so I could have missed it... I'll give it a try when I can and see if I can repro.

**Comment by Xiard** [comment]
FYI, I uninstalled the package, rebooted, did a clean build, and I’m still having VS freezes.  So I think it’s nothing to do with your package.

**Comment by thomaslevesque** [comment]
Good to know, thanks.
Good luck finding the cause of the problem!
