### ISSUE TITLE
UI stuck when load gif

### ISSUE THREAD

**Issue by fpsqdb** [XamlAnimatedGif/XamlAnimatedGif#40]
I load three gifs one time, each on have 2MB. The UI is not response when loading gif, but after gif shows, the UI get well. It seems that  the loading gif stream operation is on the UI thread. 
My environment is Windows 10 Mobile.

**Comment by thomaslevesque** [comment]
That shouldn't happen... the idea is that only the rendering is done on the UI thread. Where do you load the GIFs from? App resource, file, HTTP URL?

**Comment by fpsqdb** [comment]
http url

**Comment by thomaslevesque** [comment]
OK, I'll have a look

**Comment by fpsqdb** [comment]
maybe i'm wrong, it happened a few hours before, now i try again and it's works fine. I can't remember what did i change. Strange.

**Comment by thomaslevesque** [comment]
Remote images are cached locally; you're probably hitting the cache now

**Comment by thomaslevesque** [comment]
I was unable to reproduce the bug in WPF or WinRT (not tried on Windows 10 mobile because I don't have a device yet). Can you still reproduce if you clear the app's temp directory?

**Comment by fpsqdb** [comment]
No, works fine, I should write a wrong code.
