### ISSUE TITLE
CPU performance

### ISSUE THREAD

**Issue by fpsqdb** [XamlAnimatedGif/XamlAnimatedGif#41]
I have tried many ways to show GIF in my project. but i cant find a way that have both good cpu performance and memory usage. I tried [this](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/XamlAnimatedGif), it's a microsoft uwp sample use [Win2D](https://github.com/Microsoft/win2d) show GIF, because it use GPU to render image so it have  good cpu performance but it have memory leak. XamlAnimatedGif is a good project, but it use CPU to render image, when show many GIFs at a same time, there will be a performance issue especially on ARM device.  Do you have interest or plan to let XamlAnimatedGif make better use of the GPU?

**Comment by thomaslevesque** [comment]
The Win2D sample looks interesting, I'll have a look.

> Do you have interest or plan to let XamlAnimatedGif make better use of the GPU?

Interest, yes, but not plan at this point. I don't know anything about GPU programming...

**Comment by thomaslevesque** [comment]
Closing in favor of #88
