### ISSUE TITLE
Possible or there is a view that only inside the program without saving in the settings file? 

### ISSUE THREAD

**Issue by yunushkin88** [XamlAnimatedGif/XamlAnimatedGif#42]
Hello thomaslevesque!!! I loved Your library. But I don't know very well C#. Before that I wrote in C under microcontrollers. But I always try to write on C#. Maybe my question will seem trivial. Is it possible to change using your library Gif parametry of the picture. We have opened a gif and changed the frame rate in the gif or the background and closed the gif. The description says that it is possible or there is a view that only inside the program without saving in the settings file?

**Comment by thomaslevesque** [comment]
I'm not sure I understand what you're asking... Do you want to change the framerate of the GIF animation? The library doesn't support this; you can just control the number of repetitions (1 time, N times, forever, for 1 minute, etc)

**Comment by yunushkin88** [comment]
Okay, so the option Frame delay in the description of the library is just a pause rather than the frame rate. Thanks.

**Comment by thomaslevesque** [comment]
> Okay, so the option Frame delay in the description of the library is just a pause rather than the frame rate. Thanks.

No, the frame delay in the description just refers to the fact that the library reads and uses the delay encoded in each frame. This table is there just to show which aspects of a GIF image the library supports.
