### ISSUE TITLE
Failed to add XamlAnimatedGif to C++/Cx Windows Store App!

### ISSUE THREAD

**Issue by chmsee** [XamlAnimatedGif/XamlAnimatedGif#44]
XamlAnimatedGif is a Class Library, could not use for C++ or Javascript project.
XamlAnimatedGif should support C++ or Javascript project at next version?

**Comment by thomaslevesque** [comment]
Hi,

It's a .NET library, so it only works with .NET.
To make it work with C++ projects I think it would have to be a WinRT component, but I don't know how to do that, and I don't know C++ well enough to do that.
For JavaScript, I don't think you need a library at all... animated GIFs are supported natively in HTML
