### ISSUE TITLE
doesnt work when image embed in a RichTextBlock

### ISSUE THREAD

**Issue by qinqingege** [XamlAnimatedGif/XamlAnimatedGif#46]
<RichTextBlock Name="richTextBlock" HorizontalAlignment="Left" Height="502" Margin="10,0,0,0" VerticalAlignment="Top" Width="248">
            <Paragraph>
                <InlineUIContainer>
                    <font color="#FFFF0000"><Image gif:AnimationBehavior.SourceUri="Assets/111.gif"/></font>
                </InlineUIContainer>
                Mauris auctor tincidunt auctor.
            </Paragraph>
        </RichTextBlock>

gif doesnt animate.

**Comment by thomaslevesque** [comment]
Did you close the issue on purpose? Did it work eventually? If not, please provide more details
