### ISSUE TITLE
Gif animates only in design time

### ISSUE THREAD

**Issue by bruti732** [XamlAnimatedGif/XamlAnimatedGif#47]
It seems my gif only animates in design time.

What could be wrong?

**Comment by bruti732** [comment]
![earth](https://cloud.githubusercontent.com/assets/16567060/12130782/7ddc1728-b461-11e5-9d3d-7e4d8d9aaf65.gif)

This is the gif file I used

**Comment by thomaslevesque** [comment]
How did you set the image? Could you post your code?

**Comment by bruti732** [comment]
<Image gif:AnimationBehavior.SourceUri="pack://application:,,,/TestProject;component/Images/Earth.gif" 
                   gif:AnimationBehavior.AutoStart="True"
                   Width="200" Height="200" Stretch="None"/>

**Comment by thomaslevesque** [comment]
I can't reproduce the issue, it works fine for me. Are you sure the build action for the image is set to `Resource`? If it's not, it will still work in the designer (not sure why), but it won't work at runtime.

**Comment by bruti732** [comment]
Hi Thomas,

Yes, the build action had been set to Resource. I am using Windows 8 and .NET 4.5. I am not sure if that even matters. I did see the gif animate in another PC for which I don't know the OS details. However, after reloading the window on the same PC, it did not animate again. :(

I have tried using both the XAMLAnimatedGif and WPFAnimatedGif, both produced the same results for me.

**Comment by thomaslevesque** [comment]
OK... Is the image displayed if you just set `Source="pack://application:,,,/TestProject;component/Images/Earth.gif"` ? (just to make sure it's correctly built as a resource)
Have you tried using a relative URI?

> I have tried using both the XAMLAnimatedGif and WPFAnimatedGif, both produced the same results for me.

That's really weird, because there's almost nothing in common between the implementations of the two libraries... I can't think of anything that would cause both of them to fail.

**Comment by thomaslevesque** [comment]
Also, try to add a handler for the `AnimationBehavior.Error` attached event. If it is triggered, look at the exception, it might tell you something useful.

**Comment by bruti732** [comment]
hi, the image is displayed correctly. It is just that the animation is not working. I had added the handler for the AnimationBehavior.Error but it not even gets triggered. I am sure why it is not displaying the animation.

If it this info helps, I am using Windows 10 Pro 64 Bit, and using .NET 4.5 Visual Studio 2015.

**Comment by thomaslevesque** [comment]
I have no idea what's going on... it works fine for everyone else, so perhaps you're doing something wrong. Are you able to reproduce the issue in a small project? If you can, please share the project so I can have a look.

**Comment by bruti732** [comment]
I created a small project and it works perfectly fine. :( 

The window where the animation does not work is a splash screen for my WPF application. There must be definitely something that affects the display. I will investigate further

**Comment by bruti732** [comment]
In addition, I am using the MEFBootstrapper and I call the window.Show of the window with the GIF during the CreateShell method of the Bootstrapper.

**Comment by bruti732** [comment]
the gif is for a splashscreen by the way. I saw one of your comments in StackOverflow just now

**Comment by bruti732** [comment]
all working now. just need to display the splash screen in a different thread. Thanks for being patient with my questions

**Comment by thomaslevesque** [comment]
Glad you found the solution to your problem ;)
