### ISSUE TITLE
Cannot load gif in a referenced assembly

### ISSUE THREAD

**Issue by ChinhDuong** [XamlAnimatedGif/XamlAnimatedGif#50]
I load a gif from referenced assembly by pack uri, I can see it in design mode. But in runtime mode, I cannot see it

**Comment by thomaslevesque** [comment]
Could you please post your code?
Also, make sure that the build action for the image is set to `Resource`

**Comment by ChinhDuong** [comment]
Thank your reply. I solved my problem
