### ISSUE TITLE
Silverlight support

### ISSUE THREAD

**Issue by tpola** [XamlAnimatedGif/XamlAnimatedGif#51]
Hi. 
My project consists of WPF/Silverlight applications that share almost the same code base.

I got a requirement to display animated GIFs, so I added Silverlight support to XamlAnimatedGif. It's working. Probably not bulletproof, but I'm happy with it.

I see from the readme page you're accepting contributions. 
Silverlight is kind of outdated but if you're interested just let met know.

**Comment by thomaslevesque** [comment]
Hi @tpola,

I'd be glad to accept a contribution to support Silverlight, thanks for offering! Could you please submit a pull request so that I can review the changes?

Thanks
