### ISSUE TITLE
Add support for animated ImageBrush

### ISSUE THREAD

**Issue by thomaslevesque** [XamlAnimatedGif/XamlAnimatedGif#54]
As proposed by @tpola in https://github.com/tpola/XamlAnimatedGif/commit/794aade0fe7ce4385f4f7e3e066f91ca51f7234e

There are a few scenarios where it would be useful to be able to use an animated GIF as a brush. Currently it's not possible, because the `WriteableBitmap` used for rendering (`Animator.Bitmap`) is not exposed publicly.

Also, currently client code cannot create an instance of `Animator`. The `CreateAsync` method is designed for internal use, and takes an `Image` control as a parameter, which doesn't make sense when you just want a brush.

A possible approach would be to:
- make `Animator` independent of the `Image` control (shouldn't be too hard, since currently it's only used for raising events)
- this would make the `CreateAsync` method more easily usable from client code, and it could become public
- add a `CreateBrush` method to `Animator`

**Comment by tpola** [comment]
Sounds good.
That will make the library more versatile.

**Comment by thomaslevesque** [comment]
I started working on this. Here's the approach I took so far:

- make `Animator` an abstract class, with no reference to the `Image` control
- make an internal derived class `ImageAnimator` with just the image-specific parts
- make a public derived class `BrushAnimator` with just the code related to the brush

The idea is that it will be used like this:

```
var animator =  await BrushAnimator.CreateAsync("animated.gif");
control.Background = animator.Brush;
animator.Play();
...
// stop the animation and release associated resources when we're done using the brush
animator.Dispose();
```
