### ISSUE TITLE
RepeatBehavior infinite not working for certain GIFs

### ISSUE THREAD

**Issue by Blathers** [XamlAnimatedGif/XamlAnimatedGif#57]
I have a bunch of images using the same code to set the URI source on the gif. I have set their RepeatBehavior to infinite, however I noticed it only works for some images. On others, they only run once and then stop. I can't compile the code myself, but I wonder if the only differences lay in the GIFs innate frame count settings.
Thanks for all your hard work!

**Comment by Blathers** [comment]
This is the not repeating GIF in question!
![](http://i.imgur.com/LimrmqP.gif)

**Comment by thomaslevesque** [comment]
It seems to work fine for me... Just tried it in the WPF demo app. The repeat count encoded in this image is "forever", so even if you don't set `RepeatBehavior="Forever"`, it will run forever.

Could you post the code you used?

**Comment by Blathers** [comment]
Thanks for the response, it actually seems that something about uploading the image to imgur fixed the issue for me as well. I found where I originally got the image, and taking it directly from there again still has issues:

![](https://45.media.tumblr.com/6a141d69564a29ac7d4071df5d519808/tumblr_o0rbb4TA1k1urr1ryo1_540.gif)

**Comment by thomaslevesque** [comment]
Just tried with the new image, and it still works... Could you send a link to the raw file? I'm not sure what Github does with images included in comments, but it might also transform them.

**Comment by Blathers** [comment]
Sure: here's where I got it from
http://everlastingeden.tumblr.com/post/137041867540/2-8-1-4

**Comment by thomaslevesque** [comment]
Still no luck, I can't reproduce... the animation is repeating forever by default. You still haven't shown your code; the problem might be there.

**Comment by Blathers** [comment]
You're right, it must be something in my code. I did a unit test and got this image working - I'll report back if I find anything interesting out!

**Comment by Blathers** [comment]
Dang I realized my old project had an outdated NuGet version somehow! That did the trick sorry for the trouble! Coffee on me - Cheers!
