### ISSUE TITLE
Image is white until loaded

### ISSUE THREAD

**Issue by Blathers** [XamlAnimatedGif/XamlAnimatedGif#58]
I have a static image which turns into a GIF on mouse over. This works, however there is a small delay in load time of the GIF which causes the image to temporarily turn white (while loading the URI), causing a visual flicker. Is there any way to not remove the static image source until the animated URI source is ready to be used, to allow a more seamless transition?

**Comment by thomaslevesque** [comment]
Ah, I see what you mean. The `Image.Source` is set to null very early in the process of loading the new animation. I guess this could be changed, but it's not as trivial as it seems; it might have some unexpected side effects. I'll try to think of a way to improve this.

In the meanwhile, the easiest solution is probably to use 2 images : one with the static image, and one with the GIF. You can wait for the `AnimationBehavior.Loaded` event to hide the static image.

**Comment by Blathers** [comment]
Thank you - Using two images works for the time being for what I need!
