### ISSUE TITLE
How to display a gif in RichEditBox

### ISSUE THREAD

**Issue by chfe910** [XamlAnimatedGif/XamlAnimatedGif#60]
I know how to display an Image by:
`RichEditBox.Document.Selection.InsertImage(System.Int32 width, System.Int32 height, System.Int32 ascent, VerticalCharacterAlignment verticalAlign, System.String alternateText, IRandomAccessStream value).`

but how to insert a gif with XamlAnimatedGif in RichEditBox? Does anyone have any idea?

Thanks

**Comment by thomaslevesque** [comment]
I haven't used `RichEditBox` yet, but from what I can see in the documentation, I don't think it's possible. `XamlAnimatedGif` works by providing an `ImageSource` and animating its content, but it doesn't seem possible to display an arbitrary image to `RichEditBox`, you can only pass a stream...

**Comment by chfe910** [comment]
Yes! That is the problem. I will try another solution. Thanks very much!
