### ISSUE TITLE
UWP working on desktop but not on Windows 10 Mobile

### ISSUE THREAD

**Issue by Geforcex250** [XamlAnimatedGif/XamlAnimatedGif#61]
Hi !

After deploying my working project (WUP Desktop) to a Windows 10 Mobile emulator & device, I've encountered a really weird bug that made the app crash...

> Cannot deserialize XBF metadata property list as 'SourceUri' was not found in type 'XamlAnimatedGif.AnimationBehavior'. [Line: 0 Position: 0]

After a few researches, I found that the problem might come from the way the package was built on nuget ?
https://github.com/Windows-XAML/Template10/issues/558

Hope that you'll be able to find out what is going on because your Library is awesome !

PS: AnyCPU, x86, x64 worked great on my Windows 10 computer.

Sincerely yours.

**Comment by thomaslevesque** [comment]
Hi,

Thanks for reporting this. The thing is, I never did anything to make this library work in UWP apps, it just happened to (mostly) work without any change... so I'm not really surprised that it fails in some cases. I'm not familiar with the error you mention, I don't even know what "XBF metadata" is... I'll look into it as soon as I can.

**Comment by Opiumtm** [comment]
I tested XamlAnimatedGif on Windows 10 Mobile. It works.
No crashes, just work very slow.

**Comment by thomaslevesque** [comment]
Sorry I never got around to fix this... Windows 10 Mobile is dead and buried now, so I'll close the issue.
