### ISSUE TITLE
Reusing the same stream as source

### ISSUE THREAD

**Issue by x000000** [XamlAnimatedGif/XamlAnimatedGif#62]
I've tried to use same stream twice, but it fails on reading gif's header because stream's position wasn't reset to 0 (after previous usage). It would be nice if library take care of position by itself.

**Comment by thomaslevesque** [comment]
I guess it could do that. Anyway, I should probably add some code to check that the stream is seekable, because the library won't be able to play an animation from a stream that's not seekable.

**Comment by thomaslevesque** [comment]
Fixed in 1.1.8
