### ISSUE TITLE
Expose the AnimationCompleted event on AnimationBehavior

### ISSUE THREAD

**Issue by thomaslevesque** [XamlAnimatedGif/XamlAnimatedGif#68]
Currently the only way to detect the end of the animation is to get the `Animator` object when the animation is done loading, and subscribe to its `AnimationCompleted` event. This is not very convenient, and can't be used directly in XAML.

The event could probably be exposed directly on `AnimationBehavior`, as an attached event in WPF (which would make it usable in XAML), and as a regular static event on other platforms (since they don't support custom attached events).

**Comment by thomaslevesque** [comment]
Closed by #117. Thanks @alexbereznikov!
I just published a 1.2.0 version that contains the change. Hopefully it should be indexed on NuGet soon.

**Comment by alexbereznikov** [comment]
@thomaslevesque  Glad to hear that!
