### ISSUE TITLE
Use new Composition API for UWP platform

### ISSUE THREAD

**Issue by Opiumtm** [XamlAnimatedGif/XamlAnimatedGif#69]
https://msdn.microsoft.com/library/windows/apps/dn706878

It might be more fast to use Composition API on UWP platform for rendering.

For now, even on top tier Lumia 950 smartphone GIF animation is slow and laggy.

**Comment by thomaslevesque** [comment]
Hi @Opiumtm,

Thanks for the suggestion. Unfortunately I haven't really looked at UWP yet, I don't know anything about the Composition API... If you do, I'd gladly accept some help :wink:

**Comment by thomaslevesque** [comment]
My involvement in this project has been very low for several years, and it's unlikely to increase significantly, so I'll probably never implement this. Closing.
