### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by ZeBobo5** [XamlAnimatedGif/XamlAnimatedGif#78]
Sometimes, I've got this error on WPF version :

Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at XamlAnimatedGif.Animator.Dispose(Boolean)
   at XamlAnimatedGif.Animator.Finalize()

I used the 1.1.3 version.

**Comment by thomaslevesque** [comment]
Hi @ZeBobo5,

Thanks for reporting this.

As far as I can tell, the only thing that could throw a NRE in `Dispose(bool)` is if `_timingManager` is null, which is only possible if the object wasn't created successfully (error during construction). Do you see any other exception before the one that makes the app crash? You can detect errors by subscribing to the `AnimationBehavior.Error` attached event.

**Comment by thomaslevesque** [comment]
It should be fixed in 1.1.5 which I just pushed to NuGet.

Note that it will fix the crash, but not the root cause (failure to create the `Animator` instance)
