### ISSUE TITLE
Stream instead save file to temp folder UWP

### ISSUE THREAD

**Issue by Survivon** [XamlAnimatedGif/XamlAnimatedGif#81]
Hi, I use your nuget XamlAnimatedGif in my UWP project. You save some file in temp folder. How can i use stream instead of save file. Can you add some propperty that i can choose want i save file to temp folder or use stream. 
Thanks in advance. Dmitriy

**Comment by Survivon** [comment]
@thomaslevesque 
i want set some Uri to SourceUri and your lib insted of save file and than work with it, download it to stream and work with it and maybe some propery to dispose this stream. Or can i set some stream to SourceStream and it doesn't create file in temp.

**Comment by thomaslevesque** [comment]
I'm not sure I understand what you're saying...

> Or can i set some stream to SourceStream and it doesn't create file in temp.

Setting a stream to `SourceStream` doesn't create a temporary file. The stream can be anything, but will typically be a `FileStream` or `MemoryStream`. The only case where the lib creates a temp file is when you specify an HTTP URL as `SourceUri`; it downloads to a temp file and uses that file.

**Comment by Survivon** [comment]
Thank you, i'm try this.
