### ISSUE TITLE
code behind play/pause

### ISSUE THREAD

**Issue by rafalboguski** [XamlAnimatedGif/XamlAnimatedGif#85]
As in title i try to manually start animation
`ImageBehavior.GetAnimationController(image)`
results in compilation error "The name 'ImageBehavior' does not exist in the current context"

I have used this namespace
`xmlns:gif="clr-namespace:XamlAnimatedGif;assembly=XamlAnimatedGif"`

**Comment by thomaslevesque** [comment]
Hi @rafalboguski,

The namespaces you use in XAML and the ones you use in code-behind are independant; just because you declare a xmlns mapping in XAML doesn't cause this namespace to be imported in code-behind.

You need to add a `using XamlAnimatedGif;` clause in your code-behind file.

**Comment by rafalboguski** [comment]
Thank you for fast replay, but still ImageBehavior is not recognized
![screenshot](http://i.imgur.com/VfZ9CBA.png)
Is this proper way of manual play/pause control? That was the only solution I have managed to google.

**Comment by thomaslevesque** [comment]
Ah, yes, it should be `AnimationBehavior`, not `ImageBehavior`. `ImageBehavior` was the name in my other library, WpfAnimatedGif.
