### ISSUE TITLE
Using same IMAGE for GIF and other image formats

### ISSUE THREAD

**Issue by jhwheuer** [XamlAnimatedGif/XamlAnimatedGif#91]
Hi Thomas, 
currently, I am using two IMAGE controls to display a variety of images, including GIFs. One is visible when the image is NOT a gif, using IMAGE.SOURCE in XAML. The other is alternatively visible when a GIF image is to be displayed, with AnimationBehavior.SourceUri being used.

It works, but appears a bit wasteful. 

As an alternative, I have created two string properties in the underlying DataContext, one for Non-GIF, one for GIF-Images, providing the URI to the image. The props are set to NULL if the image is GIF/Non-GIF.
That does not work. The animation is shown, but the static image is not...

Am I doing this wrong? Is there a way to alternate between GIF and non-GIF that I am not aware of, or is the two-controls-solution the way to go?

Thanks!

PS. Did you get my donation today?

**Comment by thomaslevesque** [comment]
Hi @jhwheuer,

You don't need two separate images. If you set `AnimationBehavior.SourceUri` to a non-GIF image, it will just be displayed as a static image.

> PS. Did you get my donation today?

I did! Thanks a lot :smile:

**Comment by jhwheuer** [comment]
Hmm, must be doing something wrong, because that does not happen. I am not using a URL to a web location but a URI with a local path, and that is not displayed at all... Anything I must be doing there? The path is accessible to the UWP app, as I can just set IMAGE.Source to it and it works fine...

**Comment by thomaslevesque** [comment]
Is it an absolute or relative URI?

**Comment by jhwheuer** [comment]
Absolute: c:\....

**Comment by jhwheuer** [comment]
Again, as Image.Source, that works fine.

**Comment by thomaslevesque** [comment]
That's weird... I can reproduce the issue. I see that the `file:///C:...` uri is properly assigned to the `UriSource` of the image, but the image doesn't show up. I don't really know UWP (I didn't design the library for UWP but for WinRT, and I'm pretty sure it *was* working on Windows 8)... is there anything special about file URIs as image source in UWP?

**Comment by jhwheuer** [comment]
Wait, Are you trying to assign the Source as a string? Coz that needs to be a Bitmap...

**Comment by thomaslevesque** [comment]
> Wait, Are you trying to assign the Source as a string? Coz that needs to be a Bitmap...

No, I'm assigning a `Uri` to `BitmapImage.UriSource`, then assigning the `BitmapImage` to `Image.Source`

https://github.com/XamlAnimatedGif/XamlAnimatedGif/blob/master/XamlAnimatedGif.Shared/AnimationBehavior.cs#L482-L491

**Comment by jhwheuer** [comment]
Hmmm, I had to go through SoftwareBitmap to make this work... Let me look into my code after I put my kids to bed.
THANKS

**Comment by jhwheuer** [comment]
WElcome by the way to the Bat Shit Crazy World called UWP.   UnexpectedWorldProblem...

**Comment by jhwheuer** [comment]
This is actually working...
`StorageFile file = await StorageFile.GetFileFromPathAsync(src);
                        bool r = Windows.Storage.AccessCache.StorageApplicationPermissions.FutureAccessList.CheckAccess(file);
                        if (r)
                        {
                            using (IRandomAccessStream fileStream = await file.OpenAsync(Windows.Storage.FileAccessMode.Read))
                            {
                                // Set the image source to the selected bitmap
                                _bitmap = new BitmapImage();

                                await _bitmap.SetSourceAsync(fileStream);

                            }
                        }
   `

**Comment by thomaslevesque** [comment]
Indeed, `SetSource(Stream)` seems to work... I guess I can use that.

**Comment by thomaslevesque** [comment]
Apparently setting `Bitmap.UriSource` to a `file:///` URI raises the `BitmapImage.ImageFailed` event. The error just says `E_NETWORK_ERROR` 😡. Can I join the "I hate UWP" club too?

I guess I'll just use a stream then, but it's annoying.

**Comment by thomaslevesque** [comment]
The fix is ready, I'll try to publish a release soon

**Comment by jhwheuer** [comment]
many thanks

**Comment by thomaslevesque** [comment]
Fixed in 1.1.7
