### ISSUE TITLE
DownloadProgress event not firing 

### ISSUE THREAD

**Issue by jluisestrada** [XamlAnimatedGif/XamlAnimatedGif#92]
In my project, I add the DownloadProgressHandler through the AnimationBehavior but it is never fired (All my images comes from Urls)

This is the process I do:

- Create Image instance (In code)
- Add DownloadProgressHandler
- Set AutoStart
- Add Image control to visual tree
- Set SourceUri

Am I missing something?

**Comment by thomaslevesque** [comment]
Hi @jluisestrada,

Is this an image you already downloaded before? There's a local file cache, so if you have already downloaded the image before, the local file is reused, and the download doesn't happen, so the event isn't raised. The files are cached in `%TEMP%`, and their name is the SHA1 of the URI.

To make sure this is really the cause of your problem, can you try with an image you haven't downloaded before? Or remove the cached files? If it's not that, please post the code that does what you describe.

Anyway, when the cached file is used, it should probably still raise the `DownloadProgress` event, indicating 100% progress.

**Comment by jluisestrada** [comment]
That makes totally sense. I've been using the same image over and over for my tests.

I will use a new image :)

Just as a side note, the DownloadedProgress event hasn't being fired a single time in my tests.

Let you know how it goes

Tnx
